# Generated by Django 4.0.2 on 2022-02-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
